apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: prod
type: Opaque
data:
  username: ZGVmYXVsdA==
  password: TXloZmQxWXFDSVV6ckxod1J5T2ZVVGlyaHJ1RXlUc2c=
  PINECONE_API_KEY: Mjc0MWVhYzYtNWFiZC00MjZmLTlhMzctNTM0MTk1ZTI5ODg0
  PINECONE_ENV: Z2NwLXN0YXJ0ZXI=
  HUGGINGFACEHUB_API_TOKEN: aGZfVWNiamp6ZmlVdVNrYUhxSFdhVkFrR0Rhd3l4eWNzWlJtSA==
  SPRING_DATASOURCE_USERNAME: YXp1cmV1c2Vy
  SPRING_DATASOURCE_PASSWORD: T3Vzc2FtYTIwMjQ=  
