apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
resources:
- api-service-deployment.yml
- api-service-service.yml
- chat-service-deployment.yml
- chat-service-service.yml
- databaseSecret.yml
- frontend-deployment.yml
- frontend-service.yml
- ingress.yml
- namespace.yml
- production-issuer.yml
- staging-issuer.yml
