apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
resources:
- api-service-deployment.yml
- api-service-service.yml
- chat-service-deployment.yml
- chat-service-service.yml
- databaseSecret.yml
- frontend-deployment.yml
- frontend-service.yml
- ingress.yml
- namespace.yml
- production-issuer.yml
- staging-issuer.yml
images:
- name: redahimmi/medical-chatbot-api-service
  newName: redahimmi/medical-chatbot-api-service
  newTag: af0f000a7ca799c51e4dbc891f415e2e067ce85a
- name: redahimmi/medical-chatbot-chat-service
  newName: redahimmi/medical-chatbot-chat-service
  newTag: af0f000a7ca799c51e4dbc891f415e2e067ce85a
- name: redahimmi/medical-chatbot-frontend
  newName: redahimmi/medical-chatbot-frontend
  newTag: af0f000a7ca799c51e4dbc891f415e2e067ce85a
